### ISSUE TITLE
下载专辑封面时出现未捕获异常

### ISSUE THREAD

**Issue by IIIIOvOIIII** [GameBelial/ZonyLrcToolsX#111]
您好，我在执行下载专辑封面时有未捕获异常，日志如下：

```
Lynx@Lynnx-Station MINGW64 /d/Xfer/ZonyLrcToolsX_Alpha.2022072501_win-x64
$ ls -al /c/Users/Lynx/Music/QQMusic/
total 1354213
drwxr-xr-x 1 Lynx 197121        0 Aug 16 22:40  ./
drwxr-xr-x 1 Lynx 197121        0 Aug 16 21:49  ../
-rw-r--r-- 1 Lynx 197121     2466 Aug 16 22:39  22.山海旅人.lrc
-rw-r--r-- 1 Lynx 197121 47142060 Dec 19  2021  22.山海旅人.wav
-rw-r--r-- 1 Lynx 197121 12283006 Dec 19  2021  23.玉盘散流光（PV原版）.wav
drwxr-xr-x 1 Lynx 197121        0 Aug 16 22:19  VipSongsDownload/
-rw-r--r-- 1 Lynx 197121 27093565 Aug 16 22:05 '房东的猫 _ 谢春花 - 那些花儿 (Live).flac'
-rw-r--r-- 1 Lynx 197121     1168 Aug 16 22:39 '房东的猫 _ 谢春花 - 那些花儿 (Live).lrc'
-rw-r--r-- 1 Lynx 197121   380021 Aug 16 22:29 '房东的猫 _ 谢春花 - 那些花儿 (Live).png'
-rw-r--r-- 1 Lynx 197121 22981472 Aug 16 22:05 '房东的猫 _ 谢春花 - 那些花儿 (Live_伴奏).flac'
-rw-r--r-- 1 Lynx 197121     1168 Aug 16 22:39 '房东的猫 _ 谢春花 - 那些花儿 (Live_伴奏).lrc'
-rw-r--r-- 1 Lynx 197121   380021 Aug 16 22:29 '房东的猫 _ 谢春花 - 那些花儿 (Live_伴奏).png'
-rw-r--r-- 1 Lynx 197121 18620887 Aug 16 22:17 '程璧 - Bloom-is Result-to meet a Flower.flac'
-rw-r--r-- 1 Lynx 197121      890 Aug 16 22:39 '程璧 - Bloom-is Result-to meet a Flower.lrc'
-rw-r--r-- 1 Lynx 197121   163410 Aug 16 22:27 '程璧 - Bloom-is Result-to meet a Flower.png'
-rw-r--r-- 1 Lynx 197121 26433835 Aug 16 22:17 '程璧 - Bright Star.flac'
-rw-r--r-- 1 Lynx 197121      890 Aug 16 22:39 '程璧 - Bright Star.lrc'
-rw-r--r-- 1 Lynx 197121   163410 Aug 16 22:29 '程璧 - Bright Star.png'
-rw-r--r-- 1 Lynx 197121 26925425 Aug 16 22:18 '程璧 - Dear Mary.flac'
-rw-r--r-- 1 Lynx 197121     2685 Aug 16 22:39 '程璧 - Dear Mary.lrc'
-rw-r--r-- 1 Lynx 197121  4166843 Aug 16 22:29 '程璧 - Dear Mary.png'
-rw-r--r-- 1 Lynx 197121 20619505 Aug 16 22:17 '程璧 - Good Day Hey Tokyo.flac'
-rw-r--r-- 1 Lynx 197121      890 Aug 16 22:39 '程璧 - Good Day Hey Tokyo.lrc'
-rw-r--r-- 1 Lynx 197121   163410 Aug 16 22:27 '程璧 - Good Day Hey Tokyo.png'
-rw-r--r-- 1 Lynx 197121 10226398 Aug 16 22:17 '程璧 - Hush Little Baby.flac'
-rw-r--r-- 1 Lynx 197121     2323 Aug 16 22:39 '程璧 - Hush Little Baby.lrc'
-rw-r--r-- 1 Lynx 197121    25694 Aug 16 22:28 '程璧 - Hush Little Baby.png'
-rw-r--r-- 1 Lynx 197121 22628105 Aug 16 22:16 '程璧 - Leron Leron Sinta.flac'
-rw-r--r-- 1 Lynx 197121      890 Aug 16 22:39 '程璧 - Leron Leron Sinta.lrc'
-rw-r--r-- 1 Lynx 197121   163410 Aug 16 22:27 '程璧 - Leron Leron Sinta.png'
-rw-r--r-- 1 Lynx 197121 31170114 Aug 16 22:17 '程璧 - Love at First Sight.flac'
-rw-r--r-- 1 Lynx 197121     3778 Aug 16 22:39 '程璧 - Love at First Sight.lrc'
-rw-r--r-- 1 Lynx 197121   217020 Aug 16 22:27 '程璧 - Love at First Sight.png'
-rw-r--r-- 1 Lynx 197121 22145104 Aug 16 22:16 '程璧 - Malaika.flac'
-rw-r--r-- 1 Lynx 197121 26129268 Aug 16 22:16 '程璧 - Mangwani Mpulele.flac'
-rw-r--r-- 1 Lynx 197121      890 Aug 16 22:39 '程璧 - Mangwani Mpulele.lrc'
-rw-r--r-- 1 Lynx 197121   163410 Aug 16 22:27 '程璧 - Mangwani Mpulele.png'
-rw-r--r-- 1 Lynx 197121 17200668 Aug 16 22:16 '程璧 - Shalom Chaverim.flac'
-rw-r--r-- 1 Lynx 197121      890 Aug 16 22:39 '程璧 - Shalom Chaverim.lrc'
-rw-r--r-- 1 Lynx 197121   163410 Aug 16 22:27 '程璧 - Shalom Chaverim.png'
-rw-r--r-- 1 Lynx 197121 25503335 Aug 16 22:17 '程璧 - Song.flac'
-rw-r--r-- 1 Lynx 197121  2423330 Aug 16 22:28 '程璧 - Song.png'
-rw-r--r-- 1 Lynx 197121 21371300 Aug 16 22:17 '程璧 - Sonnet 18.flac'
-rw-r--r-- 1 Lynx 197121      890 Aug 16 22:39 '程璧 - Sonnet 18.lrc'
-rw-r--r-- 1 Lynx 197121   163410 Aug 16 22:27 '程璧 - Sonnet 18.png'
-rw-r--r-- 1 Lynx 197121 21552073 Aug 16 22:17 '程璧 - The Daffodils.flac'
-rw-r--r-- 1 Lynx 197121    58446 Aug 16 22:28 '程璧 - The Daffodils.png'
-rw-r--r-- 1 Lynx 197121 20712550 Aug 16 22:16 '程璧 - To i hola.flac'
-rw-r--r-- 1 Lynx 197121      890 Aug 16 22:39 '程璧 - To i hola.lrc'
-rw-r--r-- 1 Lynx 197121   163410 Aug 16 22:40 '程璧 - To i hola.png'
-rw-r--r-- 1 Lynx 197121  9534516 Aug 16 22:17 '程璧 - Yesterday.flac'
-rw-r--r-- 1 Lynx 197121     3926 Aug 16 22:39 '程璧 - Yesterday.lrc'
-rw-r--r-- 1 Lynx 197121   179321 Aug 16 22:40 '程璧 - Yesterday.png'
-rw-r--r-- 1 Lynx 197121 38973955 Aug 16 22:15 '程璧 - 卷耳_hires.flac'
-rw-r--r-- 1 Lynx 197121     1222 Aug 16 22:39 '程璧 - 卷耳_hires.lrc'
-rw-r--r-- 1 Lynx 197121    34568 Aug 16 22:28 '程璧 - 卷耳_hires.png'
-rw-r--r-- 1 Lynx 197121 20286520 Aug 16 21:57 '程璧 - 恋恋风尘.flac'
-rw-r--r-- 1 Lynx 197121      890 Aug 16 22:39 '程璧 - 恋恋风尘.lrc'
-rw-r--r-- 1 Lynx 197121   163410 Aug 16 22:29 '程璧 - 恋恋风尘.png'
-rw-r--r-- 1 Lynx 197121 39368988 Aug 16 22:18 '程璧 - 我不想听森林所传的流言蜚语_hires.flac'
-rw-r--r-- 1 Lynx 197121     1302 Aug 16 22:39 '程璧 - 我不想听森林所传的流言蜚语_hires.lrc'
-rw-r--r-- 1 Lynx 197121    51222 Aug 16 22:28 '程璧 - 我不想听森林所传的流言蜚语_hires.png'
-rw-r--r-- 1 Lynx 197121 23986378 Aug 16 22:16 '程璧 - 摽有梅_hires.flac'
-rw-r--r-- 1 Lynx 197121      561 Aug 16 22:39 '程璧 - 摽有梅_hires.lrc'
-rw-r--r-- 1 Lynx 197121  2368009 Aug 16 22:27 '程璧 - 摽有梅_hires.png'
-rw-r--r-- 1 Lynx 197121 24795408 Aug 16 22:16 '程璧 - 撒旦的提琴.flac'
-rw-r--r-- 1 Lynx 197121     1255 Aug 16 22:39 '程璧 - 撒旦的提琴.lrc'
-rw-r--r-- 1 Lynx 197121   179574 Aug 16 22:27 '程璧 - 撒旦的提琴.png'
-rw-r--r-- 1 Lynx 197121 29678977 Aug 16 22:17 '程璧 - 朝露 feat_短歌行.flac'
-rw-r--r-- 1 Lynx 197121     1426 Aug 16 22:39 '程璧 - 朝露 feat_短歌行.lrc'
-rw-r--r-- 1 Lynx 197121   841570 Aug 16 22:27 '程璧 - 朝露 feat_短歌行.png'
-rw-r--r-- 1 Lynx 197121 28228254 Aug 16 22:15 '程璧 - 木瓜_hires.flac'
-rw-r--r-- 1 Lynx 197121      726 Aug 16 22:39 '程璧 - 木瓜_hires.lrc'
-rw-r--r-- 1 Lynx 197121   121629 Aug 16 22:40 '程璧 - 木瓜_hires.png'
-rw-r--r-- 1 Lynx 197121 40597873 Aug 16 22:16 '程璧 - 桃夭_hires.flac'
-rw-r--r-- 1 Lynx 197121   107291 Aug 16 22:28 '程璧 - 桃夭_hires.png'
-rw-r--r-- 1 Lynx 197121 49378982 Aug 16 22:15 '程璧 - 汉广_hires.flac'
-rw-r--r-- 1 Lynx 197121     1228 Aug 16 22:39 '程璧 - 汉广_hires.lrc'
-rw-r--r-- 1 Lynx 197121   176463 Aug 16 22:29 '程璧 - 汉广_hires.png'
-rw-r--r-- 1 Lynx 197121 28006853 Aug 16 22:16 '程璧 - 百万朵玫瑰花.flac'
-rw-r--r-- 1 Lynx 197121   316190 Aug 16 22:27 '程璧 - 百万朵玫瑰花.png'
-rw-r--r-- 1 Lynx 197121 29085829 Aug 16 22:17 '程璧 - 童神.flac'
-rw-r--r-- 1 Lynx 197121      973 Aug 16 22:39 '程璧 - 童神.lrc'
-rw-r--r-- 1 Lynx 197121   163410 Aug 16 22:28 '程璧 - 童神.png'
-rw-r--r-- 1 Lynx 197121 43889224 Aug 16 22:16 '程璧 - 绿衣_hires.flac'
-rw-r--r-- 1 Lynx 197121      890 Aug 16 22:39 '程璧 - 绿衣_hires.lrc'
-rw-r--r-- 1 Lynx 197121 38325861 Aug 16 22:15 '程璧 - 草虫_hires.flac'
-rw-r--r-- 1 Lynx 197121      908 Aug 16 22:39 '程璧 - 草虫_hires.lrc'
-rw-r--r-- 1 Lynx 197121    36309 Aug 16 22:27 '程璧 - 草虫_hires.png'
-rw-r--r-- 1 Lynx 197121 51233509 Aug 16 22:15 '程璧 - 葛生_hires.flac'
-rw-r--r-- 1 Lynx 197121      908 Aug 16 22:39 '程璧 - 葛生_hires.lrc'
-rw-r--r-- 1 Lynx 197121    36309 Aug 16 22:28 '程璧 - 葛生_hires.png'
-rw-r--r-- 1 Lynx 197121 10191939 Aug 16 22:15 '程璧 - 蝉鸣_hires.flac'
-rw-r--r-- 1 Lynx 197121     6342 Aug 16 22:39 '程璧 - 蝉鸣_hires.lrc'
-rw-r--r-- 1 Lynx 197121   153576 Aug 16 22:27 '程璧 - 蝉鸣_hires.png'
-rw-r--r-- 1 Lynx 197121 54090441 Aug 16 22:16 '程璧 - 黍离_hires.flac'
-rw-r--r-- 1 Lynx 197121      919 Aug 16 22:39 '程璧 - 黍离_hires.lrc'
-rw-r--r-- 1 Lynx 197121   163410 Aug 16 22:27 '程璧 - 黍离_hires.png'
-rw-r--r-- 1 Lynx 197121 30053516 Aug 16 22:05 '胡海泉 _ 谢春花 - 送你一朵小红花 (Live).flac'
-rw-r--r-- 1 Lynx 197121     1543 Aug 16 22:39 '胡海泉 _ 谢春花 - 送你一朵小红花 (Live).lrc'
-rw-r--r-- 1 Lynx 197121    54450 Aug 16 22:29 '胡海泉 _ 谢春花 - 送你一朵小红花 (Live).png'
-rw-r--r-- 1 Lynx 197121 27031444 Aug 16 22:05 '胡海泉 _ 谢春花 - 送你一朵小红花 (Live_伴奏).flac'
-rw-r--r-- 1 Lynx 197121     1543 Aug 16 22:39 '胡海泉 _ 谢春花 - 送你一朵小红花 (Live_伴奏).lrc'
-rw-r--r-- 1 Lynx 197121    54450 Aug 16 22:40 '胡海泉 _ 谢春花 - 送你一朵小红花 (Live_伴奏).png'
-rw-r--r-- 1 Lynx 197121 26936860 Aug 16 22:05 '谢春花 - Summer Bossa (Live).flac'
-rw-r--r-- 1 Lynx 197121     1697 Aug 16 22:39 '谢春花 - Summer Bossa (Live).lrc'
-rw-r--r-- 1 Lynx 197121 21502015 Aug 16 22:05 '谢春花 - 一棵会开花的树 (Live).flac'
-rw-r--r-- 1 Lynx 197121     1886 Aug 16 22:39 '谢春花 - 一棵会开花的树 (Live).lrc'
-rw-r--r-- 1 Lynx 197121  1666970 Aug 16 22:28 '谢春花 - 一棵会开花的树 (Live).png'
-rw-r--r-- 1 Lynx 197121 25042883 Aug 16 22:05 '谢春花 - 借我 (Live).flac'
-rw-r--r-- 1 Lynx 197121     2878 Aug 16 22:39 '谢春花 - 借我 (Live).lrc'
-rw-r--r-- 1 Lynx 197121  7571354 Aug 16 22:28 '谢春花 - 借我 (Live).png'
-rw-r--r-- 1 Lynx 197121 26739152 Aug 16 22:05 '谢春花 - 往事随风 (伴奏).flac'
-rw-r--r-- 1 Lynx 197121     1775 Aug 16 22:39 '谢春花 - 往事随风 (伴奏).lrc'
-rw-r--r-- 1 Lynx 197121    31889 Aug 16 22:28 '谢春花 - 往事随风 (伴奏).png'
-rw-r--r-- 1 Lynx 197121 28265226 Aug 16 22:05 '谢春花 - 往事随风.flac'
-rw-r--r-- 1 Lynx 197121     1775 Aug 16 22:39 '谢春花 - 往事随风.lrc'
-rw-r--r-- 1 Lynx 197121    31889 Aug 16 22:40 '谢春花 - 往事随风.png'
-rw-r--r-- 1 Lynx 197121 31567007 Aug 16 22:05 '谢春花 - 心空空 (Live).flac'
-rw-r--r-- 1 Lynx 197121     1496 Aug 16 22:39 '谢春花 - 心空空 (Live).lrc'
-rw-r--r-- 1 Lynx 197121  1823067 Aug 16 22:28 '谢春花 - 心空空 (Live).png'
-rw-r--r-- 1 Lynx 197121 35216926 Aug 16 22:05 '谢春花 - 我一定会爱上你 (Live).flac'
-rw-r--r-- 1 Lynx 197121     1792 Aug 16 22:39 '谢春花 - 我一定会爱上你 (Live).lrc'
-rw-r--r-- 1 Lynx 197121  1823067 Aug 16 22:29 '谢春花 - 我一定会爱上你 (Live).png'
-rw-r--r-- 1 Lynx 197121 24357070 Aug 16 22:05 '谢春花 - 我从崖边跌落 (Live).flac'
-rw-r--r-- 1 Lynx 197121     1866 Aug 16 22:39 '谢春花 - 我从崖边跌落 (Live).lrc'
-rw-r--r-- 1 Lynx 197121 22992335 Aug 16 22:05 '谢春花 - 求得 (Live).flac'
-rw-r--r-- 1 Lynx 197121     1175 Aug 16 22:39 '谢春花 - 求得 (Live).lrc'
-rw-r--r-- 1 Lynx 197121  1666970 Aug 16 22:28 '谢春花 - 求得 (Live).png'
-rw-r--r-- 1 Lynx 197121 26370519 Aug 16 22:05 '谢春花 - 洛干的吻 (Live).flac'
-rw-r--r-- 1 Lynx 197121     2438 Aug 16 22:39 '谢春花 - 洛干的吻 (Live).lrc'
-rw-r--r-- 1 Lynx 197121  1666970 Aug 16 22:28 '谢春花 - 洛干的吻 (Live).png'
-rw-r--r-- 1 Lynx 197121 28032214 Aug 16 22:05 '谢春花 - 荒岛 (Live).flac'
-rw-r--r-- 1 Lynx 197121     1747 Aug 16 22:39 '谢春花 - 荒岛 (Live).lrc'
-rw-r--r-- 1 Lynx 197121   224685 Aug 16 22:28 '谢春花 - 荒岛 (Live).png'
-rw-r--r-- 1 Lynx 197121 20827700 Aug 16 22:05 '谢春花 - 黑夜虽长，请别用来遗忘 (Live).flac'
-rw-r--r-- 1 Lynx 197121     1498 Aug 16 22:39 '谢春花 - 黑夜虽长，请别用来遗忘 (Live).lrc'
-rw-r--r-- 1 Lynx 197121   115360 Aug 16 22:28 '谢春花 - 黑夜虽长，请别用来遗忘 (Live).png'

Lynx@Lynnx-Station MINGW64 /d/Xfer/ZonyLrcToolsX_Alpha.2022072501_win-x64
$ ./ZonyLrcTools.Cli.exe download -d "C:\Users\Lynx\Music\QQMusic" -a -n 1
[00:18:05 INF] 已经扫描到了 49 个音乐文件。
[00:18:05 INF] 开始加载音乐文件的标签信息...
[00:18:06 WRN] C:\Users\Lynx\Music\QQMusic\23.玉盘散流光（PV原版）.wav 没有找到正确的标签信息，请考虑调整正则表达式。
[00:18:06 INF] 已成功加载 49 个音乐文件的标签信息。
[00:18:06 INF] 开始下载专辑图像数据...
[00:18:06 INF] 歌曲名: 黑夜虽长，请别用来遗忘, 艺术家: 谢春花, 下载成功.
[00:18:07 INF] 歌曲名: 荒岛, 艺术家: 谢春花, 下载成功.
[00:18:07 INF] 歌曲名: 洛干的吻, 艺术家: 谢春花, 下载成功.
[00:18:07 INF] 歌曲名: 求得, 艺术家: 谢春花, 下载成功.
[00:18:07 INF] 歌曲名: 我从崖边跌落, 艺术家: 谢春花, 下载成功.
[00:18:08 INF] 歌曲名: 我一定会爱上你, 艺术家: 谢春花, 下载成功.
[00:18:08 INF] 歌曲名: 心空空, 艺术家: 谢春花, 下载成功.
[00:18:08 INF] 歌曲名: 往事随风, 艺术家: 谢春花, 下载成功.
[00:18:08 INF] 歌曲名: 往事随风, 艺术家: 谢春花, 下载成功.
[00:18:09 INF] 歌曲名: 借我, 艺术家: 谢春花, 下载成功.
[00:18:09 INF] 歌曲名: 一棵会开花的树, 艺术家: 谢春花, 下载成功.
[00:18:09 INF] 歌曲名: Summer Bossa, 艺术家: 谢春花, 下载成功.
[00:18:10 INF] 歌曲名: 送你一朵小红花, 艺术家: 胡海泉, 下载成功.
[00:18:10 INF] 歌曲名: 送你一朵小红花, 艺术家: 胡海泉, 下载成功.
[00:18:11 INF] 歌曲名: 黍离, 艺术家: 程璧, 下载成功.
[00:18:11 INF] 歌曲名: 蝉鸣, 艺术家: 程璧, 下载成功.
[00:18:11 INF] 歌曲名: 葛生, 艺术家: 程璧, 下载成功.
[00:18:11 INF] 歌曲名: 草虫, 艺术家: 程璧, 下载成功.
[00:18:12 INF] 歌曲名: 绿衣, 艺术家: 程璧, 下载成功.
[00:18:12 INF] 歌曲名: 童神, 艺术家: 程璧, 下载成功.
[00:18:12 INF] 歌曲名: 百万朵玫瑰花, 艺术家: 程璧, 下载成功.
[00:18:12 INF] 歌曲名: 汉广, 艺术家: 程璧, 下载成功.
[00:18:12 INF] 歌曲名: 桃夭, 艺术家: 程璧, 下载成功.
[00:18:13 INF] 歌曲名: 木瓜, 艺术家: 程璧, 下载成功.
[00:18:13 INF] 歌曲名: 朝露 feat.短歌行, 艺术家: 程璧, 下载成功.
[00:18:14 INF] 歌曲名: 撒旦的提琴, 艺术家: 程璧, 下载成功.
[00:18:14 INF] 歌曲名: 摽有梅, 艺术家: 程璧, 下载成功.
[00:18:15 INF] 歌曲名: 我不想听森林所传的流言蜚语, 艺术家: 程璧, 下载成功.
[00:18:15 INF] 歌曲名: 恋恋风尘, 艺术家: 程璧, 下载成功.
[00:18:15 INF] 歌曲名: 卷耳, 艺术家: 程璧, 下载成功.
[00:18:15 INF] 歌曲名: Yesterday, 艺术家: 程璧, 下载成功.
[00:18:16 INF] 歌曲名: To i hola, 艺术家: 程璧, 下载成功.
[00:18:16 INF] 歌曲名: The Daffodils, 艺术家: 程璧, 下载成功.
[00:18:16 INF] 歌曲名: Sonnet 18, 艺术家: 程璧, 下载成功.
[00:18:17 INF] 歌曲名: Song, 艺术家: 程璧, 下载成功.
[00:18:17 INF] 歌曲名: Shalom Chaverim, 艺术家: 程璧, 下载成功.
[00:18:18 INF] 歌曲名: Mangwani Mpulele, 艺术家: 程璧, 下载成功.
[00:18:18 INF] 歌曲名: Malaika, 艺术家: 程璧, 下载成功.
[00:18:18 INF] 歌曲名: Love at First Sight, 艺术家: 程璧, 下载成功.
[00:18:19 INF] 歌曲名: Leron Leron Sinta, 艺术家: 程璧, 下载成功.
[00:18:19 INF] 歌曲名: Hush Little Baby, 艺术家: 程璧, 下载成功.
[00:18:19 INF] 歌曲名: Good Day Hey Tokyo, 艺术家: 程璧, 下载成功.
[00:18:19 INF] 歌曲名: Dear Mary, 艺术家: 程璧, 下载成功.
[00:18:20 INF] 歌曲名: Bright Star, 艺术家: 程璧, 下载成功.
[00:18:20 INF] 歌曲名: Bloom-is Result-to meet a Flower, 艺术家: 程璧, 下载成功.
[00:18:20 INF] 歌曲名: 那些花儿, 艺术家: 房东的猫, 下载成功.
[00:18:21 INF] 歌曲名: 那些花儿, 艺术家: 房东的猫, 下载成功.
[00:18:21 INF] 歌曲名: 22.ɽ������, 艺术家: KALA��Dana Kendall�����Ψ, 下载成功.
[00:18:22 ERR] 出现了未处理的异常: 请求的名称有效，但是找不到请求的类型的数据。 (p1.music.126.net:443)
调用栈:
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String , Int32 , HttpRequestMessage , Boolean , CancellationToken )
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage , Boolean , CancellationToken )
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage , Boolean , CancellationToken )
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage )
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken )
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage , Boolean , CancellationToken )
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage , Boolean , Boolean , CancellationToken )
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage , Boolean , CancellationToken )
   at System.Net.Http.HttpClient.GetByteArrayAsyncCore(HttpRequestMessage , CancellationToken )
   at ZonyLrcTools.Cli.Infrastructure.Album.NetEase.NetEaseAlbumDownloader.DownloadAsync(String songName, String artist)
   at ZonyLrcTools.Cli.Commands.SubCommand.DownloadCommand.DownloadAlbumTaskLogicAsync(IAlbumDownloader downloader, MusicInfo info)
   at ZonyLrcTools.Cli.Commands.SubCommand.DownloadCommand.<>c__DisplayClass35_1.<<DownloadAlbumAsync>b__3>d.MoveNext()
--- End of stack trace from previous location ---
   at ZonyLrcTools.Cli.Infrastructure.Threading.WarpTask.RunAsync(Func`1 taskFactory, CancellationToken cancellationToken)
   at ZonyLrcTools.Cli.Commands.SubCommand.DownloadCommand.DownloadAlbumAsync(ImmutableList`1 musicInfos)
   at ZonyLrcTools.Cli.Commands.SubCommand.DownloadCommand.OnExecuteAsync(CommandLineApplication app)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.InvokeAsync(MethodInfo method, Object instance, Object[] arguments)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.Hosting.CommandLine.Internal.CommandLineService`1.RunAsync(CancellationToken cancellationToken)
   at McMaster.Extensions.Hosting.CommandLine.Internal.CommandLineLifetime.<>c__DisplayClass10_0.<<WaitForStartAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Extensions.Hosting.HostExtensions.RunCommandLineApplicationAsync(IHost host, CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostBuilderExtensions.RunCommandLineApplicationAsync[TApp](IHostBuilder hostBuilder, String[] args, Action`1 configure,
CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostBuilderExtensions.RunCommandLineApplicationAsync[TApp](IHostBuilder hostBuilder, String[] args, CancellationToken ca
ncellationToken)
   at ZonyLrcTools.Cli.Program.Main(String[] args)

Lynx@Lynnx-Station MINGW64 /d/Xfer/ZonyLrcToolsX_Alpha.2022072501_win-x64
$

```

系统是Win10 21H1，如有其他troubleshooting需要可以联系我。谢谢作者

**Comment by real-zony** [comment]
@lingxide 能将 歌曲名: 22.ɽ������, 艺术家: KALA��Dana Kendall�����Ψ, 下载成功. 这首歌曲文件上传一下吗？

**Comment by IIIIOvOIIII** [comment]
Hi @real-zony 
```
Lynx@Lynnx-Station MINGW64 ~/Music/QQMusic
$ ls -al 22*
-rw-r--r-- 1 Lynx 197121     2466 Aug 16 22:39 22.山海旅人.lrc
-rw-r--r-- 1 Lynx 197121    96007 Aug 17 00:18 22.山海旅人.png
-rw-r--r-- 1 Lynx 197121 47142060 Dec 19  2021 22.山海旅人.wav

Lynx@Lynnx-Station MINGW64 ~/Music/QQMusic
$ md5sum 22*
72ca1fe23941d23ab021b9956c639982 *22.山海旅人.lrc
4b4666387d4b7399324144c10483c502 *22.山海旅人.png
c0676518095b61f9a7c60413fb5e163d *22.山海旅人.wav

Lynx@Lynnx-Station MINGW64 ~/Music/QQMusic
$ ls -al 23*
-rw-r--r-- 1 Lynx 197121 12283006 Dec 19  2021 23.玉盘散流光（PV原版）.wav

Lynx@Lynnx-Station MINGW64 ~/Music/QQMusic
$ md5sum 23*
5aeba6331f81c926dde58a47cbe0f777 *23.玉盘散流光（PV原版）.wav

Lynx@Lynnx-Station MINGW64 ~/Music/QQMusic
$
```
[22.山海旅人.wav](https://tmp.link/f/62fcfd63d5ee4)

[23.玉盘散流光（PV原版）.wav](https://tmp.link/f/62fcfd674fd53)

**Comment by real-zony** [comment]
@lingxide 临时解决方法是将这些无法正常读取 tag 信息的文件复制到单独的文件夹，并且在标签加载器中禁用掉 taglib，使用文件名解析器。如果不能解决，请重新打开此 Issue。
```YAML
  # 下载器的相关参数配置。
  provider:
    # 标签扫描器的相关参数配置。
    tag:
      # 支持的标签扫描器。
      plugin:
        - name: Taglib    # 基于 Taglib 库的标签扫描器。
          priority: -1     # 优先级，升序排列。
        - name: FileName  # 基于文件名的标签扫描器。
          priority: 2
          # 基于文件名扫描器的扩展参数。
          extensions:
            # 正则表达式，用于匹配文件名中的作者信息和歌曲信息，可根据
            # 自己的需求进行调整。
            regularExpressions: "(?'artist'.+)\\s-\\s(?'name'.+)"
```
