### ISSUE TITLE
当程序添加到 windows系统的PATH 环境变量时，软件无法运行

### ISSUE THREAD

**Issue by kimycai** [GameBelial/ZonyLrcToolsX#128]
全局环境，即在windows环境变量里设置到path里，可以不用每次执行时都要切换到ZonyLrcToolsX所在的目录下执行，提高执行效率和适配性

**Comment by real-zony** [comment]
可以自行添加到 environment 的 path.

**Comment by kimycai** [comment]
> 可以自行添加到 environment 的 path.

添加了不起作用，有错误

**Comment by real-zony** [comment]
> > 可以自行添加到 environment 的 path.
> 
> 添加了不起作用，有错误

什么错误信息呢？能贴上来我看看吗？

**Comment by kimycai** [comment]
> > > 可以自行添加到 environment 的 path.
> > 
> > 
> > 添加了不起作用，有错误
> 
> 什么错误信息呢？能贴上来我看看吗？

Unhandled exception. System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Resources\error_msg.json'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.File.OpenText(String path)
   at ZonyLrcTools.Common.Infrastructure.Exceptions.ErrorCodeHelper.LoadErrorMessage() in /home/runner/work/ZonyLrcToolsX/ZonyLrcToolsX/src/ZonyLrcTools.Common/Infrastructure/Exceptions/ErrorCodeHelper.cs:line 29
   at ZonyLrcTools.Cli.Program.ConfigureErrorMessage() in /home/runner/work/ZonyLrcToolsX/ZonyLrcToolsX/src/ZonyLrcTools.Cli/Program.cs:line 50
   at ZonyLrcTools.Cli.Program.Main(String[] args) in /home/runner/work/ZonyLrcToolsX/ZonyLrcToolsX/src/ZonyLrcTools.Cli/Program.cs:line 32
   at ZonyLrcTools.Cli.Program.<Main>(String[] args)
