### ISSUE TITLE
下载歌曲的时候报错了，大佬帮忙看看是我哪里弄错了吗

### ISSUE THREAD

**Issue by liuyu12** [GameBelial/ZonyLrcToolsX#160]
D:\ZonyLrcTools>ZonyLrcTools.Cli.exe download -d "I:/Music/歌曲" -a -n -2
[18:17:37 INF] Starting...
[18:17:37 INF] 已经扫描到了 3 个音乐文件。
[18:17:37 INF] 开始加载音乐文件的标签信息...
[18:17:37 ERR] 出现了未处理的异常: Specified argument was out of the range of valid values. (Parameter 'maxDegreeOfParallelism')
调用栈:
   at ZonyLrcTools.Common.Infrastructure.Threading.WarpTask..ctor(Int32 maxDegreeOfParallelism)
   at ZonyLrcTools.Common.MusicInfoLoader.LoadAsync(IReadOnlyCollection`1 filePaths, Int32 parallelCount, CancellationToken cancellationToken)
   at ZonyLrcTools.Common.MusicInfoLoader.

**Comment by real-zony** [comment]
@liuyu12 把 `-2` 改成 `2` 就行，如下:
```
ZonyLrcTools.Cli.exe download -d "I:/Music/歌曲" -a -n 2
```
