### ISSUE TITLE
下载封面报错了

### ISSUE THREAD

**Issue by hankuksui** [GameBelial/ZonyLrcToolsX#68]
2020年08月18日 13:54:47 - 产生了异常。
异常提示信息：Unable to read data from the transport connection: The connection was closed.
异常堆栈信息：   at System.Net.ConnectStream.EndRead(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.WebExceptionWrapperStream.EndRead(IAsyncResult asyncResult)
   at System.Net.Http.StreamToStreamCopy.BufferReadCallback(IAsyncResult ar)

**Comment by real-zony** [comment]
请尝试 0.1.9.5 版本，如果还有问题可以重新打开本问题。
