### ISSUE TITLE
批量下载歌词时发现报错

### ISSUE THREAD

**Issue by ForeverBRS** [GameBelial/ZonyLrcToolsX#82]
数量为19首
其中有一首名称很长，是否与文件名或ID3标签有关？
有一首没有歌词，是否没有歌词也会报错？
报错信息：
[14:25:53 ERR] 出现了未处理的异常: Object reference not set to an instance of an object.
调用栈:
   at ZonyLrcTools.Cli.Infrastructure.Lyric.NetEase.NetEaseLyricDownloader.GenerateLyricAsync(Byte[] data, LyricDownloaderArgs args)
   at ZonyLrcTools.Cli.Infrastructure.Lyric.LyricDow

运行信息：
![image](https://user-images.githubusercontent.com/43440593/147727324-5debfbb6-f097-4028-a03f-011a2fb25ef8.png)

**Comment by ForeverBRS** [comment]
批量处理366首歌曲出现如下报错

[21:32:50 ERR] 出现了未处理的异常: Object reference not set to an instance of an object.
调用栈:
   at ZonyLrcTools.Cli.Infrastructure.Lyric.NetEase.NetEaseLyricDownloader.GenerateLyricAsync(Byte[] data, LyricDownloaderArgs args)
   at ZonyLrcTools.Cli.Infrastructure.Lyric.LyricDownloader.DownloadAsync(String songName, String artist)
   at ZonyLrcTools.Cli.Commands.DownloadCommand.<>c__DisplayClass28_0.<<DownloadLyricTaskLogicAsync>g__InternalDownloadLogicAsync|0>d.MoveNext()
--- End of stack trace from previous location ---
   at ZonyLrcTools.Cli.Commands.DownloadCommand.DownloadLyricTaskLogicAsync(IEnumerable`1 downloaderList, MusicInfo info)
   at ZonyLrcTools.Cli.Commands.DownloadCommand.<>c__DisplayClass27_1.<<DownloadLyricFilesAsync>b__2>d.MoveNext()
--- End of stack trace from previous location ---
   at ZonyLrcTools.Cli.Infrastructure.Threading.WarpTask.RunAsync(Func`1 taskFactory, CancellationToken cancellationToken)
   at ZonyLrcTools.Cli.Commands.DownloadCommand.DownloadLyricFilesAsync(ImmutableList`1 musicInfos)
   at ZonyLrcTools.Cli.Commands.DownloadCommand.OnExecuteAsync(CommandLineApplication app)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.InvokeAsync(MethodInfo method, Object instance, Object[] arguments)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.Hosting.CommandLine.Internal.CommandLineService`1.RunAsync(CancellationToken cancellationToken)
   at McMaster.Extensions.Hosting.CommandLine.Internal.CommandLineLifetime.<>c__DisplayClass10_0.<<WaitForStartAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Extensions.Hosting.HostExtensions.RunCommandLineApplicationAsync(IHost host, CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostBuilderExtensions.RunCommandLineApplicationAsync[TApp](IHostBuilder hostBuilder, String[] args, Action`1 configure, CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostBuilderExtensions.RunCommandLineApplicationAsync[TApp](IHostBuilder hostBuilder, String[] args, CancellationToken cancellationToken)
   at ZonyLrcTools.Cli.Commands.ToolCommand.Main(String[] args)

**Comment by real-zony** [comment]
@ForeverBRS 能否上传比较长的歌曲名称文件，我这边试一下。

**Comment by ForeverBRS** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by ForeverBRS** [comment]
> @ForeverBRS 能否上传比较长的歌曲名称文件，我这边试一下。
[example.zip](https://github.com/real-zony/ZonyLrcToolsX/files/7805499/example.zip)
这个可以测试

**Comment by real-zony** [comment]
@ForeverBRS 能上传一下原始歌曲文件吗？

**Comment by ForeverBRS** [comment]
> @ForeverBRS 能上传一下原始歌曲文件吗？
github不支持音频文件上传
![image](https://user-images.githubusercontent.com/43440593/148148441-772fb3ca-da81-4879-8a0d-ab6dfafd7023.png)

**Comment by ForeverBRS** [comment]
我压缩包里就是音频文件

**Comment by real-zony** [comment]
@ForeverBRS 压缩包我解压出来是 LRC。
![image](https://user-images.githubusercontent.com/3907132/148152427-99a17123-0fe4-4c0c-842e-0dd3a935ddad.png)

**Comment by ForeverBRS** [comment]
@real-zony 不好意思，搞错了
传输链接：https://cowtransfer.com/s/22c165ec815849 或 打开【奶牛快传】cowtransfer.com 使用传输口令：jx1rm7 提取；
不知道为啥GitHub又不能放文件了

**Comment by real-zony** [comment]
@ForeverBRS 这首歌曲我能够正常下载，你可以试试这个版本，他会告诉你具体错误的歌曲文件。
[ZonyLrcToolsX_Alpha.2022010501_win-x64.zip](https://github.com/real-zony/ZonyLrcToolsX/files/7815643/ZonyLrcToolsX_Alpha.2022010501_win-x64.zip)

**Comment by ForeverBRS** [comment]
@real-zony 使用你发的版本之后，仍有部分歌曲下载歌词报错，但是文件的ID3是正常的

报错信息：
[14:12:09 ERR] 下载歌词文件时发生错误：Object reference not set to an instance of an object.，歌曲名: シンデレラ (Giga First Night Remix)，歌手: DECO 27 ギガP。

报错歌曲文件：
传输链接：https://cowtransfer.com/s/a9b3eff190f046 或 打开【奶牛快传】cowtransfer.com 使用传输口令：mh3k01 提取；

**Comment by real-zony** [comment]
@ForeverBRS 请下载最新的版本再试: https://github.com/real-zony/ZonyLrcToolsX/releases/tag/Alpha.2022010601
