### ISSUE TITLE
批量下载报错

### ISSUE THREAD

**Issue by zhang11lei11** [GameBelial/ZonyLrcToolsX#83]
`2022-01-05 14:37:06.155 +08:00 [ERR] 出现了未处理的异常: Object reference not set to an instance of an object.
调用栈:
   at ZonyLrcTools.Cli.Infrastructure.Extensions.LoggerExtensions.LogMusicInfoWithInformation(ILogger logger, MusicInfo musicInfo)
   at ZonyLrcTools.Cli.Commands.DownloadCommand.<>c__DisplayClass28_0.<<DownloadLyricTaskLogicAsync>g__InternalDownloadLogicAsync|0>d.MoveNext()
--- End of stack trace from previous location ---
   at ZonyLrcTools.Cli.Commands.DownloadCommand.DownloadLyricTaskLogicAsync(IEnumerable`1 downloaderList, MusicInfo info)
   at ZonyLrcTools.Cli.Commands.DownloadCommand.<>c__DisplayClass27_1.<<DownloadLyricFilesAsync>b__2>d.MoveNext()
--- End of stack trace from previous location ---
   at ZonyLrcTools.Cli.Infrastructure.Threading.WarpTask.RunAsync(Func`1 taskFactory, CancellationToken cancellationToken)
   at ZonyLrcTools.Cli.Commands.DownloadCommand.DownloadLyricFilesAsync(ImmutableList`1 musicInfos)
   at ZonyLrcTools.Cli.Commands.DownloadCommand.OnExecuteAsync(CommandLineApplication app)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.InvokeAsync(MethodInfo method, Object instance, Object[] arguments)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.Hosting.CommandLine.Internal.CommandLineService`1.RunAsync(CancellationToken cancellationToken)
   at McMaster.Extensions.Hosting.CommandLine.Internal.CommandLineLifetime.<>c__DisplayClass10_0.<<WaitForStartAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Extensions.Hosting.HostExtensions.RunCommandLineApplicationAsync(IHost host, CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostBuilderExtensions.RunCommandLineApplicationAsync[TApp](IHostBuilder hostBuilder, String[] args, Action`1 configure, CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostBuilderExtensions.RunCommandLineApplicationAsync[TApp](IHostBuilder hostBuilder, String[] args, CancellationToken cancellationToken)
   at ZonyLrcTools.Cli.Commands.ToolCommand.Main(String[] args)
2022-01-05 14:37:33.236 +08:00 [ERR] 出现了未处理的异常: Object reference not set to an instance of an object.`

**Comment by real-zony** [comment]
@zhang11lei11 你好，请尝试这个版本的文件，他会告诉你具体的错误歌曲。你可以将对应的歌曲文件上传给我，帮助我进行错误定位。
[ZonyLrcToolsX_Alpha.2022010501_win-x64.zip](https://github.com/real-zony/ZonyLrcToolsX/files/7815654/ZonyLrcToolsX_Alpha.2022010501_win-x64.zip)

**Comment by real-zony** [comment]
@zhang11lei11 请下载最新的版本再试: https://github.com/real-zony/ZonyLrcToolsX/releases/tag/Alpha.2022010601
