### ISSUE TITLE
小白完全不懂什么意思....作者可以出个最早的那种软件吗

### ISSUE THREAD

**Issue by fansaitiya** [GameBelial/ZonyLrcToolsX#90]
2022-04-04 04:57:02.867 +08:00 [ERR] 出现了未处理的异常，错误代码: 50007，错误信息: TagLib 标签读取器出现了预期之外的异常。
调用栈:
   at ZonyLrcTools.Cli.Infrastructure.Tag.TaglibTagInfoProvider.LoadAsync(String filePath) in D:\Project\OpenSource\ZonyLrcToolsX\src\ZonyLrcTools.Cli\Infrastructure\Tag\TaglibTagInfoProvider.cs:line 41
   at ZonyLrcTools.Cli.Infrastructure.Tag.DefaultTagLoader.LoadTagAsync(String filePath) in D:\Project\OpenSource\ZonyLrcToolsX\src\ZonyLrcTools.Cli\Infrastructure\Tag\DefaultTagLoader.cs:line 43
   at ZonyLrcTools.Cli.Commands.SubCommand.DownloadCommand.<>c__DisplayClass25_1.<<LoadMusicInfoAsync>b__2>d.MoveNext() in D:\Project\OpenSource\ZonyLrcToolsX\src\ZonyLrcTools.Cli\Commands\SubCommand\DownloadCommand.cs:line 105
--- End of stack trace from previous location ---
   at ZonyLrcTools.Cli.Infrastructure.Threading.WarpTask.RunAsync[T](Func`1 taskFactory, CancellationToken cancellationToken) in D:\Project\OpenSource\ZonyLrcToolsX\src\ZonyLrcTools.Cli\Infrastructure\Threading\WarpTask.cs:line 50
   at ZonyLrcTools.Cli.Commands.SubCommand.DownloadCommand.LoadMusicInfoAsync(IReadOnlyCollection`1 files) in D:\Project\OpenSource\ZonyLrcToolsX\src\ZonyLrcTools.Cli\Commands\SubCommand\DownloadCommand.cs:line 106
   at ZonyLrcTools.Cli.Commands.SubCommand.DownloadCommand.OnExecuteAsync(CommandLineApplication app) in D:\Project\OpenSource\ZonyLrcToolsX\src\ZonyLrcTools.Cli\Commands\SubCommand\DownloadCommand.cs:line 68
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.InvokeAsync(MethodInfo method, Object instance, Object[] arguments)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.Hosting.CommandLine.Internal.CommandLineService`1.RunAsync(CancellationToken cancellationToken)
   at McMaster.Extensions.Hosting.CommandLine.Internal.CommandLineLifetime.<>c__DisplayClass10_0.<<WaitForStartAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Extensions.Hosting.HostExtensions.RunCommandLineApplicationAsync(IHost host, CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostBuilderExtensions.RunCommandLineApplicationAsync[TApp](IHostBuilder hostBuilder, String[] args, Action`1 configure, CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostBuilderExtensions.RunCommandLineApplicationAsync[TApp](IHostBuilder hostBuilder, String[] args, CancellationToken cancellationToken)
   at ZonyLrcTools.Cli.Program.Main(String[] args) in D:\Project\OpenSource\ZonyLrcToolsX\src\ZonyLrcTools.Cli\Program.cs:line 29
#

**Comment by real-zony** [comment]
closed by https://github.com/real-zony/ZonyLrcToolsX/commit/ffd76f5f2ba3d7a5b4457c99a1d6848bdf69bd65
