### ISSUE TITLE
windows下 映射的网络磁盘无法访问

### ISSUE THREAD

**Issue by hyperlook** [GameBelial/ZonyLrcToolsX#99]
F盘为局域网内 映射的网络驱动器

`Unhandled exception. System.IO.DirectoryNotFoundException: Could not find a part of the path 'F:\music\album\王心凌\Resources\error_msg.json'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String , FileMode , FileAccess , FileShare , FileOptions )
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String , FileMode , FileAccess , FileShare , FileOptions , Int64 )
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String , FileMode , FileAccess , FileShare , FileOptions , Int64 )
   at System.IO.Strategies.SyncWindowsFileStreamStrategy..ctor(String , FileMode , FileAccess , FileShare , FileOptions , Int64 )
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String , FileMode , FileAccess , FileShare , FileOptions , Int64 )
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream , String , FileMode , FileAccess , FileShare , Int32 , FileOptions , Int64 )
   at System.IO.FileStream..ctor(String , FileMode , FileAccess , FileShare , Int32 , FileOptions , Int64 )
   at System.IO.FileStream..ctor(String , FileMode , FileAccess , FileShare , Int32 , FileOptions )
   at System.IO.FileStream..ctor(String , FileMode , FileAccess , FileShare , Int32 , Boolean )
   at System.IO.FileStream..ctor(String , FileMode , FileAccess , FileShare , Int32 )
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String , Encoding , Int32 )
   at System.IO.StreamReader..ctor(String , Encoding , Boolean , Int32 )
   at System.IO.StreamReader..ctor(String , Boolean )
   at System.IO.StreamReader..ctor(String )
   at System.IO.File.OpenText(String )
   at ZonyLrcTools.Cli.Infrastructure.Exceptions.ErrorCodeHelper.LoadErrorMessage() in D:\Project\OpenSource\ZonyLrcToolsX\src\ZonyLrcTools.Cli\Infrastructure\Exceptions\ErrorCodeHelper.cs:line 32
   at ZonyLrcTools.Cli.Commands.ToolCommand.ConfigureErrorMessage() in D:\Project\OpenSource\ZonyLrcToolsX\src\ZonyLrcTools.Cli\Commands\ToolCommand.cs:line 42
   at ZonyLrcTools.Cli.Commands.ToolCommand.Main(String[] args) in D:\Project\OpenSource\ZonyLrcToolsX\src\ZonyLrcTools.Cli\Commands\ToolCommand.cs:line 24
   at ZonyLrcTools.Cli.Commands.ToolCommand.<Main>(String[] args)`

**Comment by kimycai** [comment]
我的网络映射可以正常访问下载

**Comment by real-zony** [comment]
无法复现，请检查是否网络连接是否不稳定，导致程序报错，如果有任何问题请重新打开 Issue。
